ENV_CELERY_CONFIG = 'celery_config'

TASK_ID_KEY = 'id'
TASK_ID_SEPARATOR = '-'

RESPONSE_FIELD_ID = 'id'
RESPONSE_FIELD_STATUS = 'status'
RESPONSE_FIELD_RESULT = 'result'

STATUS_SUCCESS = 'SUCCESS'
STATUS_FAILURE = 'FAILURE'

