ENV_CELERY_CONFIG = 'celery_config'

TASK_ID_KEY = 'id'
TASK_ID_SEPARATOR = '-'

RESPONSE_FIELD_ID = 'id'
RESPONSE_FIELD_STATUS = 'status'
RESPONSE_FIELD_RESULT = 'result'
RESPONSE_FIELD_STATUS_CODE = 'status_code'

STATUS_CODE_OK = 200
STATUS_CODE_ACCEPTED = 202
STATUS_CODE_BAD_REQUEST = 400
STATUS_CODE_CONFLICT = 409
STATUS_CODE_ERROR = 500

